# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

kernel_linear_cpp <- function(x1, x2, sigma_f) {
    .Call('_gpssinternal_kernel_linear_cpp', PACKAGE = 'gpssinternal', x1, x2, sigma_f)
}

kernel_se_cpp <- function(x1, x2, sigma_f, l) {
    .Call('_gpssinternal_kernel_se_cpp', PACKAGE = 'gpssinternal', x1, x2, sigma_f, l)
}

kernel_periodic_cpp <- function(x1, x2, sigma_f, l, p) {
    .Call('_gpssinternal_kernel_periodic_cpp', PACKAGE = 'gpssinternal', x1, x2, sigma_f, l, p)
}

log_marginal_likelihood_cpp <- function(K, y, s2) {
    .Call('_gpssinternal_log_marginal_likelihood_cpp', PACKAGE = 'gpssinternal', K, y, s2)
}

kernel_gaussian <- function(x1, x2, b) {
    .Call('_gpssinternal_kernel_gaussian', PACKAGE = 'gpssinternal', x1, x2, b)
}

kernel_symmetric_gaussian <- function(x, b) {
    .Call('_gpssinternal_kernel_symmetric_gaussian', PACKAGE = 'gpssinternal', x, b)
}

kernel_gaussian_linear <- function(x1, x2, b) {
    .Call('_gpssinternal_kernel_gaussian_linear', PACKAGE = 'gpssinternal', x1, x2, b)
}

kernel_symmetric_gaussian_linear <- function(x, b) {
    .Call('_gpssinternal_kernel_symmetric_gaussian_linear', PACKAGE = 'gpssinternal', x, b)
}

kernel_gaussian_quadratic <- function(x1, x2, b) {
    .Call('_gpssinternal_kernel_gaussian_quadratic', PACKAGE = 'gpssinternal', x1, x2, b)
}

kernel_symmetric_gaussian_quadratic <- function(x, b) {
    .Call('_gpssinternal_kernel_symmetric_gaussian_quadratic', PACKAGE = 'gpssinternal', x, b)
}

kernel_gaussian_periodic_linear <- function(x1, x2, b, period) {
    .Call('_gpssinternal_kernel_gaussian_periodic_linear', PACKAGE = 'gpssinternal', x1, x2, b, period)
}

kernel_symmetric_gaussian_periodic_linear <- function(x, b, period) {
    .Call('_gpssinternal_kernel_symmetric_gaussian_periodic_linear', PACKAGE = 'gpssinternal', x, b, period)
}

kernel_gaussian_periodic_quadratic <- function(x1, x2, b, period) {
    .Call('_gpssinternal_kernel_gaussian_periodic_quadratic', PACKAGE = 'gpssinternal', x1, x2, b, period)
}

kernel_symmetric_gaussian_periodic_quadratic <- function(x, b, period) {
    .Call('_gpssinternal_kernel_symmetric_gaussian_periodic_quadratic', PACKAGE = 'gpssinternal', x, b, period)
}

